---
- hosts: jira
  tasks:
  - name: Stop jira
    service: name=jira state=stopped
    
  - name: Copy dbconfig xml
    template: src="/root/atlassian-subutai-master/dbconfig.xml.j2"   dest="/var/atlassian/application-data/jira/dbconfig.xml"   mode=777
    
  - name: Start jira
    service: name=jira state=started
